### ISSUE TITLE
Error in building

### ISSUE THREAD

**Issue by AkhzarFarhan** [tuanpham-dev/react-invoice-generator#5]
I am getting ERROR: 
`TypeScript error in /home/akhzarfarhan/gh/react-invoice-generator/src/styles/compose.ts(4,45):`
`Namespace 'ReactPDF' has no exported member 'Style'.  TS2694`

describing as:
`
4 | const compose = (classes: string): ReactPDF.Style => {
`

**Comment by devsafarian** [comment]
Same here

**Comment by tuanpham-dev** [comment]
This has been fixed. Please pull the latest commit.
